databases:
  - name: careertracker-db
    databaseName: careertracker
    user: careertracker

services:
  - type: web
    name: careertracker-backend
    env: python
    plan: free
    rootDir: careertracker
    buildCommand: pip install -r requirements.txt && python manage.py migrate --fake-initial && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --fake-initial && gunicorn careertracker.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /health/
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: careertracker-db
          property: connectionString
