# Generated by Django 6.0.2 on 2026-02-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('role_type', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=30)),
                ('salary_est', models.IntegerField(blank=True, null=True)),
                ('resume_match', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('GHOSTED', 'Ghosted'), ('INTERVIEW', 'Interview'), ('REPLIED', 'Replied')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=500)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
