# Generated by Django 6.0.2 on 2026-02-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='contacts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(blank=True, choices=[('LINKEDIN', 'LinkedIn'), ('REFERRAL', 'Referral'), ('JOB_PORTAL', 'Job Portal'), ('COMPANY_WEBSITE', 'Company Website'), ('COLLEGE', 'College / Campus'), ('NETWORKING', 'Networking'), ('RECRUITER', 'Recruiter'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
