# Generated by Django 6.0.2 on 2026-02-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_contacts_jobapplication_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
