# Generated by Django 6.0.2 on 2026-02-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_remote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='link',
            new_name='application_link',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='remote',
            new_name='is_remote',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(null=True, upload_to='../static/'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_at', models.DateTimeField()),
                ('interview_with', models.CharField(max_length=100)),
                ('meeting_link', models.URLField(max_length=500)),
                ('type', models.CharField(choices=[('HR', 'Hr'), ('BEHAVIOURAL', 'Behavioural'), ('TECHNICAL', 'Technical'), ('MANAGERIAL', 'Managerial'), ('GD', 'Gd'), ('OTHERS', 'Others')], max_length=15)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
            ],
        ),
    ]
