# Generated by Django 6.0.2 on 2026-02-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_link_jobapplication_application_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
