# Generated by Django 6.0.2 on 2026-02-21 14:28

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobapplication_application_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='remainder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(null=True, upload_to=jobs.models.resume_upload_path),
        ),
    ]
