# Generated by Django 6.0.2 on 2026-02-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_interview_feedback_interview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_match',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('GHOSTED', 'Ghosted'), ('INTERVIEW', 'Interview'), ('REPLIED', 'Replied'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')], max_length=10),
        ),
        migrations.CreateModel(
            name='JobDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_documents/')),
                ('file_types', models.CharField(choices=[('RESUME', 'Resume'), ('COLD EMAIL', 'Cold Email'), ('COVER LETTER', 'Cover Letter'), ('OTHERS', 'Others')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
            ],
        ),
    ]
