# Generated by Django 6.0.2 on 2026-02-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_remote',
        ),
    ]
