# Generated by Django 6.0.2 on 2026-02-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_jobapplication_is_remote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdocument',
            old_name='file_types',
            new_name='doc_types',
        ),
    ]
