# Generated by Django 6.0.2 on 2026-05-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_rename_file_types_jobdocument_doc_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.jobapplication'),
        ),
        migrations.AlterField(
            model_name='jobdocument',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.jobapplication'),
        ),
    ]
